FROM golang:alpine AS builder

WORKDIR /app
COPY . .
RUN go get ./...
RUN go build -o app ./worker/server/main.go

FROM mingyizhang/mock-server:1.0
WORKDIR /
COPY --from=builder /app/app /app/webs/mockweb/run_mock.sh /bin/
CMD ["run_mock.sh"]